name: eyes
description: "A blind helper Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  camera: ^0.8.1+7

  image:

  tflite_flutter: ^0.11.0

  animated_splash_screen: ^1.3.0
  flutter_spinkit: ^5.2.1
  page_transition: ^2.1.0

  flutter_tts: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/model/money.tflite
    - assets/model/money.txt
    - assets/model/mobilenet.tflite
    - assets/model/mobilenet.txt
    - assets/

  